---
title: "Lab10"
author: "Anna Matarazzo"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Chapter 20 Example (3 points)


```{r}
library(tibble)

bat_hat_data <- tribble(~Subject, ~Phonological_Similarity, ~Age, ~num_correct,
        "s1", "b1", "a1", 15,
        "s2", "b1", "a1", 23,
        "s3", "b1", "a1", 12,
        "s4", "b1", "a1", 16,
        "s5", "b1", "a1", 14,
        "s1", "b2", "a1", 13,
        "s2", "b2", "a1", 19,
        "s3", "b2", "a1", 10,
        "s4", "b2", "a1", 16,
        "s5", "b2", "a1", 12,
        "s6", "b1", "a2", 39,
        "s7", "b1", "a2", 31,
        "s8", "b1", "a2", 40,
        "s9", "b1", "a2", 32,
        "s10", "b1", "a2", 38,
        "s6", "b2", "a2", 29,
        "s7", "b2", "a2", 15,
        "s8", "b2", "a2", 30,
        "s9", "b2", "a2", 26,
        "s10", "b2", "a2", 30,
        )

aov_out <- aov(num_correct ~ Phonological_Similarity*Age + Error(Subject/Phonological_Similarity), data = bat_hat_data)
summary(aov_out)


```



```{r}

subjects <- c(rep(c("s1","s2","s3","s4","s5"),2),
              rep(c("s6","s7","s8","s9","s10"),2))
Phonological_Similarity <- rep(rep(c("b1","b2"),each= 5),2)
Age <- rep(c("a1","a2"), each=10)
num_correct <- c(15,23,12,16,14,
                 13,19,10,16,12,
                 39,31,40,32,38,
                 29,15,30,26,30)

bat_hat_data <- tibble(subjects,
                       Phonological_Similarity,
                       Age,
                       num_correct)

aov_out <- aov(num_correct ~ Phonological_Similarity*Age + Error(subjects/Phonological_Similarity), data = bat_hat_data)
summary(aov_out)

```




Chapter 21 Example (3 points)

```{r}

subject <- rep(c("s1", "s2", "s3", "s4"), each=10)
Typicallity_B <- rep(rep(c("b1", "b2"), each=5),4)
Faces_A <- rep(c("a1", "a2", "a3", "a4", "a5"), 8)

# Faces_A <- rep(c("a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10"), 4)

centiseconds <- c(20,22,25,24,19,37,37,43,48,45,
                  9,8,21,21,21,34,35,35,37,39,
                  18,20,18,21,33,35,39,39,37,40,
                  5,14,16,22,23,38,49,51,50,52
                  )

face_data <- tibble(subject,
                    Typicallity_B,
                    Faces_A,
                    centiseconds)

aov_out <- aov(centiseconds ~ (subject +
                                 Faces_A%in%Typicallity_B + 
                                 Typicallity_B +
                                 Typicallity_B:subject),
                                 data=face_data)

summary(aov_out)


```

